language: scala

sudo: false

jdk: oraclejdk8

scala:
  - 2.11.8
  # TODO 2.12.0 https://github.com/scalatra/scalatra-sbt.g8/issues/57

script:
  - sbt ";set g8Properties in g8 in Test ~= { _ + (\"scala_version\" -> \"$TRAVIS_SCALA_VERSION\")}; g8Test"
